In [1]:
import os

import pandas as pd

import common

# Assign notebook and folder names
notebook_name = '02_subset_counts_matrix'
figure_folder = os.path.join(common.FIGURE_FOLDER, notebook_name)
data_folder = os.path.join(common.DATA_FOLDER, notebook_name)
print('Figure folder:', figure_folder)
print('Data folder:', data_folder)

# Make the folders
! mkdir -p $figure_folder
! mkdir -p $data_folder

Figure folder: ../figures/02_subset_counts_matrix
Data folder: ../data/02_subset_counts_matrix

In [15]:
metadata_clean = pd.read_table("/home/ecwheele/cshl2017/segerstolpe_palasantza2016/data/01_subset_metadata/metadata_subset_792_cells.txt",
                               index_col=0)
print(metadata_clean.shape)
metadata_clean.head()

(792, 38)

,Comment[ENA_SAMPLE],Comment[BioSD_SAMPLE],Characteristics[organism],Characteristics[organism part],Characteristics[individual],Characteristics[single cell well quality],Characteristics[cell type],Characteristics[disease],Characteristics[sex],Characteristics[age],...,Comment[ENA_EXPERIMENT],Scan Name,Comment[SUBMITTED_FILE_NAME],Comment[ENA_RUN],Comment[FASTQ_URI],Protocol REF.3,Derived Array Data File,Comment [Derived ArrayExpress FTP file],Factor Value[disease],Factor Value[cell type]
Source Name,,,,,,,,,,,,,,,,,,,,,
HP1504901_A10,ERS1349302,SAMEA4437853,Homo sapiens,pancreas,HP1504901,OK,delta cell,normal,male,23,...,ERX1701178,HP1504901_A10.fastq.gz,HP1504901_A10.fastq.gz,ERR1630845,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR163/005/...,P-MTAB-51966,pancreas_refseq_rpkms_counts_3514sc.txt,ftp://ftp.ebi.ac.uk/pub/databases/microarray/d...,normal,delta cell
HP1504901_A16,ERS1349308,SAMEA4437859,Homo sapiens,pancreas,HP1504901,OK,beta cell,normal,male,23,...,ERX1701184,HP1504901_A16.fastq.gz,HP1504901_A16.fastq.gz,ERR1630851,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR163/001/...,P-MTAB-51966,pancreas_refseq_rpkms_counts_3514sc.txt,ftp://ftp.ebi.ac.uk/pub/databases/microarray/d...,normal,beta cell
HP1504901_A21,ERS1349314,SAMEA4437865,Homo sapiens,pancreas,HP1504901,OK,delta cell,normal,male,23,...,ERX1701190,HP1504901_A21.fastq.gz,HP1504901_A21.fastq.gz,ERR1630857,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR163/007/...,P-MTAB-51966,pancreas_refseq_rpkms_counts_3514sc.txt,ftp://ftp.ebi.ac.uk/pub/databases/microarray/d...,normal,delta cell
HP1504901_A3,ERS1349318,SAMEA4437869,Homo sapiens,pancreas,HP1504901,OK,beta cell,normal,male,23,...,ERX1701194,HP1504901_A3.fastq.gz,HP1504901_A3.fastq.gz,ERR1630861,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR163/001/...,P-MTAB-51966,pancreas_refseq_rpkms_counts_3514sc.txt,ftp://ftp.ebi.ac.uk/pub/databases/microarray/d...,normal,beta cell
HP1504901_A5,ERS1349320,SAMEA4437871,Homo sapiens,pancreas,HP1504901,OK,gamma cell,normal,male,23,...,ERX1701196,HP1504901_A5.fastq.gz,HP1504901_A5.fastq.gz,ERR1630863,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR163/003/...,P-MTAB-51966,pancreas_refseq_rpkms_counts_3514sc.txt,ftp://ftp.ebi.ac.uk/pub/databases/microarray/d...,normal,gamma cell

In [16]:
header = pd.read_table("../data/00_original/pancreas_refseq_rpkms_counts_3514sc_clean.txt",
                       nrows=1, header=None)
header = pd.Series(header.values[0][1:])
print(header.shape)
header.head()

(3514,)

0    HP1502401_N13
1    HP1502401_D14
2    HP1502401_F14
3    HP1502401_J13
4    HP1502401_B13
dtype: object

In [17]:
rpkm = pd.read_table("../data/00_original/pancreas_refseq_rpkms_counts_3514sc_clean_left.txt",
                           skiprows=1, 
                     header=None, 
                     index_col=[0,1])
rpkm.columns = header.values
print(rpkm.shape)
rpkm.head()

(26271, 3514)

,,HP1502401_N13,HP1502401_D14,HP1502401_F14,HP1502401_J13,HP1502401_B13,HP1502401_H13,HP1502401_J14,HP1502401_B14,HP1502401_A14,HP1502401_C14,...,HP1525301T2D_O10,HP1526901T2D_H2,HP1526901T2D_I16,HP1526901T2D_F7,HP1526901T2D_I23,HP1525301T2D_K3,HP1525301T2D_J10,HP1526901T2D_N8,HP1526901T2D_O11,HP1526901T2D_A8
0,1,,,,,,,,,,,,,,,,,,,,,
SGIP1,NM_032291,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,4.861786,0.0,3.102987,0.000000,0.000000,0.0,0.000000
AZIN2,NM_052998+NM_001293562,0.0,0.0,0.0,0.0,0.0,41.519287,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,24.792203,0.0,0.000000,0.000000,0.000000,0.0,14.671218
CLIC4,NM_013943,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,5.463685,0.230823,...,14.124313,9.325278,44.743017,13.234809,0.0,0.000000,0.000000,0.000000,0.0,1.740429
AGBL4,NM_032785,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,7.476933,0.000000,0.0,0.000000
NECAP2,NM_001145277+NM_001145278+NM_018090,0.0,0.0,0.0,0.0,0.0,13.992725,0.0,18.924347,44.923718,0.000000,...,0.000000,0.000000,0.000000,22.787042,0.0,1.749810,104.741197,17.744476,0.0,22.250055

In [18]:
cells_to_keep = metadata_clean.index
print(len(cells_to_keep))

792

In [19]:
cells_to_keep

Index(['HP1504901_A10', 'HP1504901_A16', 'HP1504901_A21', 'HP1504901_A3',
       'HP1504901_A5', 'HP1504901_B10', 'HP1504901_B11', 'HP1504901_B20',
       'HP1504901_B22', 'HP1504901_B23',
       ...
       'HP1526901T2D_H17', 'HP1526901T2D_H19', 'HP1526901T2D_H6',
       'HP1526901T2D_I14', 'HP1526901T2D_I15', 'HP1526901T2D_I16',
       'HP1526901T2D_I21', 'HP1526901T2D_I4', 'HP1526901T2D_I6',
       'HP1526901T2D_I7'],
      dtype='object', name='Source Name', length=792)

In [20]:
rpkm_clean = rpkm[cells_to_keep]
print(rpkm_clean.shape)
rpkm_clean.head()

(26271, 792)

,,HP1504901_A10,HP1504901_A16,HP1504901_A21,HP1504901_A3,HP1504901_A5,HP1504901_B10,HP1504901_B11,HP1504901_B20,HP1504901_B22,HP1504901_B23,...,HP1526901T2D_H17,HP1526901T2D_H19,HP1526901T2D_H6,HP1526901T2D_I14,HP1526901T2D_I15,HP1526901T2D_I16,HP1526901T2D_I21,HP1526901T2D_I4,HP1526901T2D_I6,HP1526901T2D_I7
0,1,,,,,,,,,,,,,,,,,,,,,
SGIP1,NM_032291,0.0,0.00000,0.00000,0.0,129.975704,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
AZIN2,NM_052998+NM_001293562,0.0,0.00000,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,55.163083,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
CLIC4,NM_013943,0.0,1.26208,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,44.743017,7.190192,0.000000,13.841086,0.000000
AGBL4,NM_032785,0.0,0.00000,0.00000,0.0,0.000000,0.0,0.000000,0.0,60.275883,0.0,...,0.0,0.000000,0.000000,8.175471,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
NECAP2,NM_001145277+NM_001145278+NM_018090,0.0,0.00000,25.50194,0.0,0.000000,0.0,1.572534,0.0,4.993097,0.0,...,0.0,5.427924,0.000000,74.649316,46.920391,0.000000,0.000000,23.097636,0.000000,20.835349

In [21]:
rpkm_clean.to_csv("/home/ecwheele/cshl2017/segerstolpe_palasantza2016/data/01_subset_metadata/pancreas_rpkm_792cells_clean.txt", sep="\t", encoding='utf-8' )